### ISSUE TITLE
MySQL error on custom destinations

### ISSUE THREAD

**Issue by IndigoTiger** [johnfawcett/dynroute#1]
I get the attached error when I add custom destinations to a route.
![dynroute-error](https://cloud.githubusercontent.com/assets/14924886/10268672/e7647850-6ab7-11e5-9eb8-d063ed87e4d3.png)

**Comment by johnfawcett** [comment]
On 10/04/2015 05:49 PM, Brad wrote:
>
> I get the attached error when I add custom destinations to a route.
> dynroute-error
> <https://cloud.githubusercontent.com/assets/14924886/10268672/e7647850-6ab7-11e5-9eb8-d063ed87e4d3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnfawcett/dynroute/issues/1>.
>
Can you provide info about which version of dynamic route and freepbx
you are using.

**Comment by IndigoTiger** [comment]
FreePBX: 13.0.1RC1.25
Dynamic Route: 13.0.1

I managed to fix the error by specifying the columns in the SQL command on line 326 of functions.inc.php

**Comment by johnfawcett** [comment]
Fixed in V13.0.3 - the issue was that an additional column that was no longer needed (default_dest) was left in table dynroute_dests. The install script now should remove this column if it is still present.
