### ISSUE TITLE
UNSIGNED MODULES DETECTED

### ISSUE THREAD

**Issue by kisienya** [johnfawcett/dynroute#12]
Hi,

Many thanks for this module. 

How would one go about signing this module with FreePBX to prevent the error "UNSIGNED MODULES DETECTED:"

**Comment by lgaetz** [comment]
https://wiki.freepbx.org/display/FOP/Signing+your+own+modules

**Comment by johnfawcett** [comment]
Thanks Lorne, I updated the FAQ to included the link to signing your own modules

https://www.voipsupport.it/wiki/index.php/Dynamic_Routes_FAQ#Q._What_does_the_message_.3C.3CModule_.22Dynamic_Routes.22_is_unsigned_and_should_be_re-downloaded.3E.3E_mean.3F
