### ISSUE TITLE
Using Dynamic Routes to Block unwanted calls, is there a way to simplify this?

### ISSUE THREAD

**Issue by xekon** [johnfawcett/dynroute#16]
currently I am block chaining dynamic routes, The issue is let's say I have 100 regex values that I want to test against... I do not want to have 100 dynamic routes that I have to chain together. So here is my setup as an example:

so my inbound route goes to dynamic route 1 which looks for callers whos caller ID is like V0041403400026041310 Asterisk variable:
`${REGEX("^V[0-9]*" ${CALLERID(name)})}`

If it matches, then terminate call, play service unavailable, if it does not match then goto dynamic route 2 Asterisk variable: `${REGEX("^VacuumSales$" ${CALLERID(name)})}`

If it matches, then terminate call, play service unavailable, if it does not match then goto dynamic route 3 Asterisk variable: `${REGEX("^SurveyDepartment$" ${CALLERID(name)})}`

If it matches, then terminate call, play service unavailable, if it does not match then goto dynamic route 4, otherwise send to ring group 1.

As you can see for every regex I am trying to match, the chain of dynamic route's gets longer and longer.

I am wondering if there is a way this could be checking a list of regex values in a single dynamic route.

Appreciate any help, and thank you so much for a wonderful FreePBX module.

**Comment by xekon** [comment]
We ended up storing all the names and numbers that we want to block into a mysql database, we then query the database:

`SELECT COUNT(*) FROM (SELECT phone,name FROM blacklist WHERE (name LIKE '${CALLERID(name)}' OR phone LIKE '${CALLERID(num)}') LIMIT 1) AS myvar`

**Comment by johnfawcett** [comment]
I beleive your second solution is the best one. I'm not sure what the performance implications would be of checking each caller against 100 regular expressions. In any case Dynamic Routes does not place a limit (beyond what will fit in a longtext database column) on the number of matches you can put into a a single reqular expression, providing Asterisk regex parser supports the syntax. I don't see a specification of what Regex syntax Asterisk supports so I guess you'd have to try it.
