### ISSUE TITLE
Module is unsigned

### ISSUE THREAD

**Issue by ajbattrick** [johnfawcett/dynroute#3]
The module is unsigned, causing warnings within FreePBX, and security notifications.

Can it be signed please?

![image](https://cloud.githubusercontent.com/assets/6673266/17093791/3d54779c-5243-11e6-92c6-856d85e17e84.png)

![image](https://cloud.githubusercontent.com/assets/6673266/17093779/29435782-5243-11e6-9472-bf9af431729d.png)

**Comment by johnfawcett** [comment]
I have updated the FAQ here to provide more information about this issue:

[https://www.voipsupport.it/wiki/index.php/Dynamic_Routes_FAQ#Q._What_does_the_message_.3C.3CModule_.22Dynamic_Routes.22_is_unsigned_and_should_be_re-downloaded.3E.3E_mean.3F]

I am not sure that it can be easily solved but if you have a proposed solution you are welcome to contact me.

**Comment by ajbattrick** [comment]
Thanks for the feedback John. I'll just continue to live with the warnings for now.
